version: "3"
services:
  publisher:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./publisher/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    healthcheck:
      test: pg_isready -U postgres
  subscriber:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./subscriber/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    healthcheck:
      test: pg_isready -U postgres
    depends_on:
      publisher:
        condition: service_healthy
  cascade-subscriber:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./cascade-subscriber/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    depends_on:
      subscriber:
        condition: service_healthy
