version: "3"
services:
  publisher:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./publisher/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  subscriber:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./subscriber/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    depends_on:
      - publisher
  cascade-subscriber:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./cascade-subscriber/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    depends_on:
      - subscriber
